### ISSUE TITLE
 error in the code

### ISSUE THREAD

**Issue by ProgrammerJamie** [ghidraninja/game-boy-ntgbtminer#1]
i think it is my fault but i got this error how do i fix this?

..E.......
======================================================================
ERROR: test_block_mine (__main__.TestBlock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_ntgbtminer.py", line 256, in test_block_mine
    mined_block, hash_rate = ntgbtminer.block_mine(block_vector, coinbase_message, 0, address, timeout=1, debugnonce_start=2315460000)
TypeError: block_mine() missing 1 required positional argument: 'serial_port'

----------------------------------------------------------------------
Ran 10 tests in 0.001s

FAILED (errors=1)

**Comment by nezza** [comment]
Heya, I've never run the test-suite, hence it's probably not working😆

**Comment by ProgrammerJamie** [comment]
ow xD
